# Generated by Django 5.0.4 on 2024-06-01 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amarradorapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciclo',
            name='nome',
            field=models.CharField(default='Valor Padrão', max_length=100),
        ),
        migrations.AddField(
            model_name='ciclo',
            name='texto',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
