# Generated by Django 5.0.4 on 2024-06-10 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amarradorapp', '0003_ciclo_limite_diario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciclo',
            name='nome',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField()),
                ('data', models.DateField(auto_now_add=True)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amarradorapp.ciclo')),
            ],
        ),
    ]
