# Generated by Django 5.0.4 on 2024-06-19 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amarradorapp', '0005_ciclo_dias_passados_alter_ciclo_limite_diario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='excluido',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ciclo',
            name='valor',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='valor',
            field=models.IntegerField(),
        ),
    ]
